[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_add = '''
let g:user_zen_settings = {'indentation' : '  '}
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'
depends = ['deoplete.nvim']
hook_add = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''
